# Generated by Django 5.0.7 on 2024-07-26 11:29

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=base.models.generate_uuid, editable=False, unique=True)),
                ('is_student', models.BooleanField(blank=True, default=False, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('country_code', models.CharField(blank=True, default='+91', max_length=10, null=True)),
                ('address', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', base.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ScholarShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyScholarShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='scholarship_documents')),
                ('current_school', models.CharField(max_length=255)),
                ('current_grade', models.CharField(max_length=50)),
                ('major_field_of_study', models.CharField(max_length=255)),
                ('awards_honors', models.TextField(blank=True, null=True)),
                ('relevant_courses_grades', models.TextField(blank=True, null=True)),
                ('research_projects', models.TextField(blank=True, null=True)),
                ('clubs_organizations', models.TextField(blank=True, null=True)),
                ('volunteer_work', models.TextField(blank=True, null=True)),
                ('leadership_roles', models.TextField(blank=True, null=True)),
                ('sports_competitions', models.TextField(blank=True, null=True)),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_dependents', models.IntegerField(blank=True, null=True)),
                ('financial_hardship_description', models.TextField(blank=True, null=True)),
                ('personal_essay', models.TextField(blank=True, null=True)),
                ('specific_questions', models.TextField(blank=True, null=True)),
                ('references_contact_info', models.TextField(blank=True, null=True)),
                ('letters_of_recommendation', models.FileField(blank=True, null=True, upload_to='letters_of_recommendation')),
                ('transcripts', models.FileField(blank=True, null=True, upload_to='transcripts')),
                ('resume_cv', models.FileField(blank=True, null=True, upload_to='resume_cv')),
                ('proof_of_enrollment', models.FileField(blank=True, null=True, upload_to='proof_of_enrollment')),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='passport_photos')),
                ('confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarShipProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('year_established', models.CharField(max_length=255)),
                ('provider_type', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pin_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scolarship_provider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.scholarshipprovider'),
        ),
    ]
