# Generated by Django 5.0.7 on 2024-07-28 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralGoverment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarshipprovider',
            name='user',
        ),
        migrations.AlterField(
            model_name='scholarshipprovider',
            name='provider_type',
            field=models.CharField(choices=[('organization', 'Organization (club)'), ('institution', 'Institution (Collage/School)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarshipprovider',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StateGoverment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('central_gov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.centralgoverment')),
            ],
        ),
        migrations.AddField(
            model_name='scholarshipprovider',
            name='state_gov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stategoverment'),
        ),
    ]
