# Generated by Django 5.0.7 on 2024-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_centralgoverment_remove_scholarshipprovider_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipprovider',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='pending', max_length=20),
        ),
    ]
