# Generated by Django 5.0.7 on 2024-07-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_scholarshipprovider_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='centarl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.centralgoverment'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stategoverment'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.scholarshipprovider'),
        ),
    ]
