# Generated by Django 5.0.7 on 2024-07-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_scholarship_centarl_scholarship_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='centarl',
            new_name='central',
        ),
    ]
