# Generated by Django 5.0.7 on 2024-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_centarl_scholarship_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='cast',
            field=models.CharField(blank=True, choices=[('sc_st', 'SE-ST'), ('obc', 'OBC'), ('genaral', 'Genaral')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='disability',
            field=models.CharField(blank=True, choices=[(1, 'Yes'), (0, 'No')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='education_level',
            field=models.CharField(blank=True, choices=[('10', '10'), ('plus_two', 'Plus Two'), ('ug', 'UG'), ('pg', 'PG')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='gpa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
