# Generated by Django 5.0.7 on 2024-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_scholarship_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralgoverment',
            name='lid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='centralgoverment',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stategoverment',
            name='lid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stategoverment',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
