# Generated by Django 5.0.7 on 2024-07-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_cast_user_disability_user_education_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centralgoverment',
            old_name='lid',
            new_name='provider_id',
        ),
        migrations.RenameField(
            model_name='stategoverment',
            old_name='lid',
            new_name='provider_id',
        ),
    ]
