# Generated by Django 5.0.7 on 2024-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_lid_centralgoverment_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyscholarship',
            name='central_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applyscholarship',
            name='college_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applyscholarship',
            name='state_level',
            field=models.BooleanField(default=False),
        ),
    ]
