# Generated by Django 5.0.7 on 2024-08-01 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_applyscholarship_central_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyscholarship',
            name='valid_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.scholarshipprovider'),
        ),
    ]
