# Generated by Django 5.0.7 on 2024-08-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_applyscholarship_valid_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyscholarship',
            name='central_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applyscholarship',
            name='valid_provider',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
