# Generated by Django 5.0.7 on 2024-08-02 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_applyscholarship_valid_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyscholarship',
            name='valid_provider_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.scholarshipprovider'),
        ),
        migrations.AlterField(
            model_name='applyscholarship',
            name='valid_provider',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
