# Generated by Django 5.0.7 on 2024-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_applyscholarship_central_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipprovider',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=20),
        ),
    ]
